### PR TITLE
Populate track_number for m4a files

### LINKED ISSUE #175: Track number not populated for m4a files
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Description

Based on [docs](https://mutagen.readthedocs.io/en/latest/api/mp4.html#mutagen.mp4.MP4Tags), you need to add:
```python
audio["trkn"] = [(song.track_number, song.track_count)]
```

https://github.com/deepjyoti30/ytmdl/blob/master/ytmdl/song.py#L274-L280

### PR DESCRIPTION
**Pull request by kOchirasu**
Fixes #175

### CODE REVIEW

**Comment by deepjyoti30** [comment]
@kOchirasu Thanks for the quick fix.

However, we currently have support for various metadata providers. Except `itunes`, all others do not have support for `track_count`, does, we cannot just try to fetch the track count. We will have to have a fallback for that.

Also, regarding the `track_number` field, `deezer` doesn't support that yet, so I'll add a fix for that.

But you'll have to fix the `track_count` field with some workaround!

**Comment by deepjyoti30** [comment]
@kOchirasu I have pushed the change for `deezer` on the unstable branch. Perhaps you can make the PR to that branch with the changes?

**Comment by kOchirasu** [comment]
Done.

**Comment by deepjyoti30** [comment]
@kOchirasu I understand you just made the PR to the `unstable` branch.

Can you read my previous comment before that? We need to have some kind of fallback for `track_count` since it is not supported by all providers!

**Comment by deepjyoti30** [comment]
Merged in 4218cb4

**Pull request closed without merging**
